### ISSUE TITLE
Controller - Model Connectivity? 

### ISSUE THREAD

**Issue by adictonator** [wpbones/WPBones#10]
Okay - now either I am missing out something really simple or WP Bones doesn't have a solid way to interact with the "migrations" it is creating?

How do I make a Controller - Model connection just like Laravel in  WP Bones plugin? That is like, really important.

**Comment by gfazioli** [comment]
@adictonator yes, you're right. Currently, WP Bones supports only a simple migration architecture. If you're looking for something like Eloquent or Data model, it is still in progress. This means that you have to query the database table by using the WordPress API.

**Comment by adictonator** [comment]
@gfazioli Well, if it _is_ in progress, then I am happy! 💇‍♂️

**Comment by gfazioli** [comment]
@adictonator please, have a look at `v0.9.30` where you'll find the complete Eloquent ORM implementation, let me know if everything works fine

**Comment by adictonator** [comment]
@gfazioli Woah, that was quick, man. Really excited to test that out. I'll let you know how it goes.

**Comment by gfazioli** [comment]
@adictonator you can find the docs here https://github.com/wpbones/WPBones/wiki/eloquent-orm
