### ISSUE TITLE
Eloquent Problems!

### ISSUE THREAD

**Issue by adictonator** [wpbones/WPBones#11]
The problem:-
Trying to use the eloquent's "find" function.
`eg: RoomType::find( 1 );`

- This results in the wrong table name. It appends extra "wp_" to the table name.
- When you try to update the model after "finding" it, it throws this error.
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'real.wp_wp_wp_roomtypes' doesn't exist in...`

As you can see, it appended "wp_" twice here. 

Any help would be appreciated.
Thanks.

**Comment by gfazioli** [comment]
@adictonator did you check the docs here https://github.com/wpbones/WPBones/wiki/eloquent-orm? could you drop here your model class ?

**Comment by sandeepkhehra** [comment]
@gfazioli Yeah, I did check the docs. However, here is the model I am using. Pretty vanilla. 

```
<?php
namespace RealEstateAgent\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
	protected $table = 'roomtypes';

	/**
	 * Disable Illuminate timestamp columns.
	 *
	 * @var boolean
	 */
	public $timestamps = false;

    /**
     * Get the table associated with the model.
     *
     * @return string
     */
    public function getTable()
    {
        global $wpdb;

        return $wpdb->prefix . parent::getTable();
    }
}
```

I am not sure if that's going to help.

**Comment by adictonator** [comment]
@gfazioli Yeah, I did check the docs. However, here is the model I am using. Pretty vanilla.

```
<?php
namespace RealEstateAgent\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
	protected $table = 'roomtypes';

	/**
	 * Disable Illuminate timestamp columns.
	 *
	 * @var boolean
	 */
	public $timestamps = false;

    /**
     * Get the table associated with the model.
     *
     * @return string
     */
    public function getTable()
    {
        global $wpdb;

        return $wpdb->prefix . parent::getTable();
    }
}
```
I am not sure if that's going to help.

**Comment by adictonator** [comment]
**UPDATE:**
Just for the quick patch, I am doing this. Since, it is appending the '_table prefix_' again and again (upto 3 times so far), I just implemented a check on the model level.

```
public function getTable()
    {
		global $wpdb;

		if ( strpos( parent::getTable(), $wpdb->prefix ) !== false ) {
			return parent::getTable();
		}

        return $wpdb->prefix . parent::getTable();
    }
```

**Comment by gfazioli** [comment]
@adictonator interesting, I'll check in deeper soon, thx

**Comment by adictonator** [comment]
@gfazioli Thank you. Waiting on your update. 😀

**Comment by gfazioli** [comment]
@adictonator I checked and for me, it works fine... it's pretty curious because `parent::getTable()` is the Eloquent parent class and it is not related to WordPress or WPBones. For some reason, seems that your `parent::getTable()` returns the table's name with the prefix. But it shouldn't do that at all.

Anyway, for my test I've used database table name `wp_products` and my Model is

```php
<?php

namespace WPKirk\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'products';

    /**
      * The primary key for the model.
      *
      * @var string
      */
    protected $primaryKey = 'log_id';

    /**
     * Get the table associated with the model.
     *
     * @return string
     */
    public function getTable()
    {
        global $wpdb;

        return $wpdb->prefix . parent::getTable();
    }
}
```

And I tried with

```php
var_dump(Product::find([11,12])); // OK

var_dump(Product::find(11)->activity); // OK

// OK
Product::all()->each(function ($e) {
    var_dump($e->log_id);
});```

and everything seems to work fine 🤔 

Maybe you might get more clue, for example, are you using other plugins? did you try to run `composer dump-autoload -o` ?

let me know, anyway I'll try to figure out the issue

**Comment by gfazioli** [comment]
@adictonator maybe I found, I tried with

```php
    public function getTable()
    {
        global $wpdb;

        logger(parent::getTable());

        return $wpdb->prefix . parent::getTable();
    }
```

and I got

```[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products
[22-May-2019 10:45:44 UTC] [DEBUG]: wp_products```

need to figure out why? 😄

**Comment by gfazioli** [comment]
@adictonator ok, maybe I figure out where the issue. The matter is that Eloquent call `setTable` as well. Also, the `setTable` method is called both on your class and parent. Probably, the faster solution is **remove** the property `$table` in your class, I mean you should use:

```php
<?php
namespace RealEstateAgent\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
	/**
	 * Disable Illuminate timestamp columns.
	 *
	 * @var boolean
	 */
	public $timestamps = false;

    /**
     * Get the table associated with the model.
     *
     * @return string
     */
    public function getTable()
    {
        global $wpdb;

        return $wpdb->prefix . parent::getTable();
    }
}
```
The above should works fine because Eloquent will use the class name.

So, first of all, let me know if without the `$table` property everything works fine, then I'll continue to investigate on that and I'll update the WPBones documentation as well.

**Comment by adictonator** [comment]
@gfazioli Thanks for the quick reply. However, when I remove the `$table` property from the model, I get a fatal error since my table name consists of two words ROOM-TYPE, thus it is looking for a table name `wp_room_types` whereas, WP Bones created the table with this name `wp_roomtypes`.

So, I would really like if we could also convert the PascalCase (class names) to snake case when it comes to decide the table name.

Let me know if this made any sense.

**Comment by gfazioli** [comment]
@adictonator yes, it makes sense, I'll change it in order to create `wp_room_types` from a class name `RoomType`. Regarding the issue above, for now you can use the property `$table` and replace the method `getTable` with

```php
    public function getTable()
    {
        global $wpdb;

        return $wpdb->prefix . preg_replace('/[[:<:]]' . $wpdb->prefix . '/', '', parent::getTable(), 1);

    }
```
faster solution I found atm

I'll update wpbones and docs soon, thank you for your support 👍

**Comment by adictonator** [comment]
@gfazioli Thank you. Really appreciate your work. 🙏

**Comment by gfazioli** [comment]
updated docs and code, for now close it
