### ISSUE TITLE
Issues with Deployed Plugin

### ISSUE THREAD

**Issue by adictonator** [wpbones/WPBones#13]
**Describe the bug**
When the plugin is deployed using the `php bones deploy <path-name>`, the deployed plugin's size is more than 30MB which is insane.

**To Reproduce**
1. run `php bones deploy <path-name>`
2. Right click the deployed folder.
3. Get shocked. 

**Expected behavior**
It shouldn't exceed more than 4MB in size.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - Version: 0.9.50

**Comment by gfazioli** [comment]
@adictonator hey, that's strange, could you dump the folder output? maybe the `.git` folder was not deleted 🤔

**Comment by adictonator** [comment]
@gfazioli I think I figured that out. There was this file inside the `assets` folder called `banner-1544x500.afdesign` which is around ~13MB.

Also, after the deployment, the vendor folder is around 6MB and most of the size is covered by `wpbones` folder.

Think we can reduce that?

**Comment by gfazioli** [comment]
oh yeah, for sure, we should remove the `.afdesign` template, they are needless for the deployed version. Regarding the `vendor` folder I think that it's due to *illuminate* Eloquent, because my `wpbones` folder is `719.803 byte (1 MB on disc) `

**Comment by adictonator** [comment]
Okay, so why do we need the `.afdesign` anyway?

Also, since `Eloquent` is now part of `wpbones` can we not try something to skim the size a bit? 6MB for just dependencies seems a lot to me.

Thoughts?

**Comment by gfazioli** [comment]
I'll fix the deploy flow in order to remove `.afdesign`, they are only an example.
Regarding the vendor folder, obviously, I can improve the `wpbones` folder but I cannot do the same for the illuminate/eloquent dependences... anyway, I'll try to investigate a bit on that

**Comment by adictonator** [comment]
@gfazioli Any update on this? A simple, puny plugin sizing 6MB hurt my feelings.

**Comment by gfazioli** [comment]
@adictonator just to be sure, could you provide me with your zipped ? by email, for example, in this way I'll be able to check in deeper
