### ISSUE TITLE
WPBones should not call Function WPKirk

### ISSUE THREAD

**Issue by szepeviktor** [wpbones/WPBones#20]
it is defined outside WPBones: https://github.com/wpbones/WPKirk/blob/74eb313873a19c9047fc9af25d67f8f00663e07c/index.php#L51

discovered by @phpstan

**Comment by szepeviktor** [comment]
```
 ------ ----------------------------
  Line   Foundation/Log/Log.php
 ------ ----------------------------
  22     Function WPKirk not found.
 ------ ----------------------------

 ------ ----------------------------
  Line   Foundation/Plugin.php
 ------ ----------------------------
  356    Function WPKirk not found.
 ------ ----------------------------

 ------ ----------------------------
  Line   helpers.php
 ------ ----------------------------
  201    Function WPKirk not found.
  204    Function WPKirk not found.
 ------ ----------------------------
```

**Comment by szepeviktor** [comment]
Please consider using PHPStan: https://packagist.org/packages/szepeviktor/phpstan-wordpress

**Comment by gfazioli** [comment]
@szepeviktor `WPKirk` is the base Plugin used to develop with WPBones, as you know you can't use the same PHP namespace in the WordPress environment. because we could have more one plugin written by WPBones. For this reason, always you have to start from WPKirk. You can find more info on https://github.com/wpbones/WPBones/wiki/naming-your-plugin

**Comment by szepeviktor** [comment]
@gfazioli I agree with you on the business side.
But the technical implementation is flawed.

**Comment by gfazioli** [comment]
@szepeviktor yes, in the end, it is not perfect but that's due to WordPress... the rule is that you have to rename your namespace with a unique keyword, in short, your plugin namespace. For this reason, there is `php bones` command which helps you to achieve that
