### ISSUE TITLE
Could add " Illuminate\Support\Facades\DB " for db operaction

### ISSUE THREAD

**Issue by rfrkk** [wpbones/WPBones#22]
Sometimes the orm looks bulky for some relatively complex SQL operations, so could you add the
 " Illuminate\Support\Facades\DB " .

Thank you very much.

**Comment by sbc640964** [comment]
Is there a chance for that?

**Comment by gfazioli** [comment]
Hi,
Illuminate package is now out of the box due to WordPress namespace issue.
Have a look at https://github.com/wpbones/WPBones/wiki/eloquent-orm
