### ISSUE TITLE
sidebar menu entries disappears by changing namaspace through php bones rename command

### ISSUE THREAD

**Issue by dev-talha-anwar** [wpbones/WPBones#25]
when we change namespace by php bones rename command the sidebar menu disappears once we undo the renaming (i.e. default namespace ) the menu appears again.

1. install wp kirk demo version 
2. rename the plugin by php bones rename "some name"
3. refresh the wp admin and menu is gone
4. rename plugin back to default 
5. the menu appears again

**Expected behavior**
rename commad should be fixed 

![image](https://user-images.githubusercontent.com/56028813/130307946-a9c14c35-d92d-46ef-9ed3-8f2acc7c4c22.png)
![image](https://user-images.githubusercontent.com/56028813/130307967-d5ea0239-6010-4b46-bce3-6d2bb02b14a1.png)

**Comment by dev-talha-anwar** [comment]
not able to check since bones command is not working

**Comment by gfazioli** [comment]
maybe you have got an old version - did you try with the latest?

**Comment by dev-talha-anwar** [comment]
I tried to run the command with latest version but now php bones command
does not show any output

**Comment by dev-talha-anwar** [comment]
Also bones commands are not working

**Comment by dev-talha-anwar** [comment]
command now works i am able to see the menu entries but changing the name does not change asset file name

**Comment by gfazioli** [comment]
what do you mean by "asset file name" exactly?
could you provide me with a complete example?

**Comment by gfazioli** [comment]
@dev-talha-anwar hi, please, try to update to the latest version here https://wpbones.vercel.app/

**Comment by gfazioli** [comment]
@dev-talha-anwar To participate more actively in discussions and stay updated on proposals and latest releases, I would be pleased if you joined the [WP Bones community on Discord](https://discord.gg/5bdVyycU8F).

**Comment by gfazioli** [comment]
@dev-talha-anwar this issue is fixed on v1.4.9
