### ISSUE TITLE
Can't find docs on processing forms with routes. 

### ISSUE THREAD

**Issue by jpu4** [wpbones/WPBones#31]
Hi I'm digging your plugin so far!

Now we want to show some custom forms on the front end. Is there a way to set form action to controller routes to process the form data? Couldn't find any other example in the docs other than options. 

Thanks in advance!

**Comment by gfazioli** [comment]
actually, WPBones is focused just on the backend side at the moment.
Anyway, you could process the data form as usual. Feel free to provide me with more details, just to discuss if it is worth adding some new features to the kernel 😃

**Comment by gfazioli** [comment]
@jpu4 To participate more actively in discussions and stay updated on proposals and latest releases, I would be pleased if you joined the [WP Bones community on Discord](https://discord.gg/5bdVyycU8F).
