### ISSUE TITLE
Can this framework use in themes?

### ISSUE THREAD

**Issue by iwillhappy1314** [wpbones/WPBones#4]
Can this framework use in themes? or the routers used to build frontend page?

**Comment by gfazioli** [comment]
@iwillhappy1314 currently, no, you cannot. This framework provides a set of tools for the plugins along with the routes for admin backend. It doesn't work for the frontend, even if you can write a plugin with frontend interaction.

**Comment by iwillhappy1314** [comment]
ok, got it.
