### ISSUE TITLE
Check deprecated on WPBones/WPKirk

### ISSUE THREAD

**Issue by gfazioli** [wpbones/WPBones#41]
```
PHP Deprecated:  Creation of dynamic property WPKirk\WPBones\Database\DB::$attributes is deprecated in /Valet/wpbones/wp-content/plugins/WPKirk/vendor/wpbones/wpbones/src/Database/Support/Model.php on line 168
```

**Comment by balazsnasz** [comment]
We can add `#[\AllowDynamicProperties]` to `WPBones\src\Database\DB.php` above the class declaration.
I tried it and the deprecated warning disappeared.

[https://www.php.net/manual/en/class.allowdynamicproperties.php](https://www.php.net/manual/en/class.allowdynamicproperties.php)

Although I am not totally sure if this is the good way to go. What do you think?

**Comment by gfazioli** [comment]
@balazsnasz yep, that could be a fix

anyway, the warning is due to https://github.com/wpbones/WPBones/blob/master/src/Database/Support/Model.php#L168

and could be fixed by adding

```php
  /**
   * A key-value array of attributes of the attributes.
   *
   * @var array
   */
  public $attributes = [];
``` 
on https://github.com/wpbones/WPBones/blob/master/src/Database/DB.php#L18

wdyt?

**Comment by gfazioli** [comment]
@balazsnasz create PR #43

**Comment by balazsnasz** [comment]
I tested it, and your solution seems better. It is solving the issue instead of just suppressing it. I am merging your PR.
