### ISSUE TITLE
WPBannerize()

### ISSUE THREAD

**Issue by way5** [wpbones/WPBones#9]
Hello! Going through the code of this framework I found the following:

```
wp_enqueue_script($this->slug . Str::slug($file),
--
380 | WPBannerize()->js . '/' . $file,
```

May someone explain to what this method WPBannerize refers?

**Comment by gfazioli** [comment]
@way5 it's used to load any scripts in the default folder. In particular, the `WPBannerize()->js` is a dynamic property

```php
    protected function getJsAttribute()
    {
        return "{$this->baseUri}/public/js";
    }
```
